
import __ASTRO_IMAGE_IMPORT_Z14daL6 from "../../assets/background.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprueba1-galeria.md";
import __ASTRO_IMAGE_IMPORT_9Pbhy from "../../assets/spooky_merch.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprueba2.md";
import __ASTRO_IMAGE_IMPORT_1YeKTH from "../../assets/background.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprimera-convivencia.md";
import __ASTRO_IMAGE_IMPORT_Z1NcUWg from "../../assets/primera_convivencia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprimera-convivencia.md";
import __ASTRO_IMAGE_IMPORT_Z3ndXM from "../../assets/primera_convivencia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprimera-convivencia-premios.md";
import __ASTRO_IMAGE_IMPORT_ZJPuIU from "../../assets/premios_primera_convivencia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprimera-convivencia-premios.md";
import __ASTRO_IMAGE_IMPORT_P3xze from "../../assets/primera_convivencia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprimera-convivencia-asistentes.md";
import __ASTRO_IMAGE_IMPORT_Z2wEgvI from "../../assets/asistentes_chiapas.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprimera-convivencia-asistentes.md";
import __ASTRO_IMAGE_IMPORT_Z1f5wK5 from "../../assets/primera_convivencia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Ffuncion-zumpango.md";
import __ASTRO_IMAGE_IMPORT_2au5c3 from "../../assets/funcion_zumpango.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Ffuncion-zumpango.md";
import __ASTRO_IMAGE_IMPORT_2aDDqQ from "../../assets/funcion_zumpango.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Ffuncion-chiapas.md";
import __ASTRO_IMAGE_IMPORT_Z1zFgYf from "../../assets/funcion_chiapas.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Ffuncion-chiapas.md";
import __ASTRO_IMAGE_IMPORT_kKCqc from "../../assets/funcion_zumpango.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Ffuncion-guanajuato.md";
import __ASTRO_IMAGE_IMPORT_1Mmvb5 from "../../assets/funcion_guanajuato.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Ffuncion-guanajuato.md";
export default new Map([["../../assets/background.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprueba1-galeria.md", __ASTRO_IMAGE_IMPORT_Z14daL6], ["../../assets/spooky_merch.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprueba2.md", __ASTRO_IMAGE_IMPORT_9Pbhy], ["../../assets/background.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprimera-convivencia.md", __ASTRO_IMAGE_IMPORT_1YeKTH], ["../../assets/primera_convivencia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprimera-convivencia.md", __ASTRO_IMAGE_IMPORT_Z1NcUWg], ["../../assets/primera_convivencia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprimera-convivencia-premios.md", __ASTRO_IMAGE_IMPORT_Z3ndXM], ["../../assets/premios_primera_convivencia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprimera-convivencia-premios.md", __ASTRO_IMAGE_IMPORT_ZJPuIU], ["../../assets/primera_convivencia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprimera-convivencia-asistentes.md", __ASTRO_IMAGE_IMPORT_P3xze], ["../../assets/asistentes_chiapas.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Fprimera-convivencia-asistentes.md", __ASTRO_IMAGE_IMPORT_Z2wEgvI], ["../../assets/primera_convivencia.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Ffuncion-zumpango.md", __ASTRO_IMAGE_IMPORT_Z1f5wK5], ["../../assets/funcion_zumpango.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Ffuncion-zumpango.md", __ASTRO_IMAGE_IMPORT_2au5c3], ["../../assets/funcion_zumpango.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Ffuncion-chiapas.md", __ASTRO_IMAGE_IMPORT_2aDDqQ], ["../../assets/funcion_chiapas.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Ffuncion-chiapas.md", __ASTRO_IMAGE_IMPORT_Z1zFgYf], ["../../assets/funcion_zumpango.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Ffuncion-guanajuato.md", __ASTRO_IMAGE_IMPORT_kKCqc], ["../../assets/funcion_guanajuato.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fgallery%2Ffuncion-guanajuato.md", __ASTRO_IMAGE_IMPORT_1Mmvb5]]);
		